### ISSUE TITLE
Look into ReadOnlyMany option for data volumes

### ISSUE THREAD

**Issue by rzinkstok** [EYRA-Benchmark/project-backlog#44]
Datasets (input for algorithm) is now loaded from the object store for each job. With large datasets this is a lot of network traffic! It might be possible to use persistent volumes that allow reading by multiple pods on multiple nodes simultaneously. The access mode should be ReadOnlyMany, which is not available on every provider. Cephfs should work. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/ for details.

**Comment by Tommos0** [comment]
Well the files have to come from somewhere, also with ceph. But it might help if not all data is used by the algorithm, or if the data transfer to the object storage is expensive (then we can cache it on our own nodes with ceph or glusterfs).
